spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ruogu_like?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
    url: jdbc:mysql://192.168.31.7:4000/ruogu_like
    username: root
    password:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 5000
  pulsar:
    client:
      service-url: pulsar://192.168.44.128:6650
    admin:
      service-url: http://192.168.44.128:8080
